### ISSUE TITLE
get_weblogo memory error

### ISSUE THREAD

**Issue by sefakilic** [ErillLab/collectf#17]
```
Traceback (most recent call last):

  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/local/collecTF/base/views.py", line 57, in get_weblogo
    return HttpResponse(bioutils.weblogo_uri(sites), "text/plain")

  File "/local/collecTF/base/bioutils.py", line 237, in weblogo_uri
    image_data = weblogo(sequences)

  File "/local/collecTF/base/bioutils.py", line 165, in weblogo
    stdout=PIPE, stdin=PIPE, stderr=PIPE, close_fds=True)

  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)

  File "/usr/lib64/python2.6/subprocess.py", line 1144, in _execute_child
    self.pid = os.fork()

OSError: [Errno 12] Cannot allocate memory


<WSGIRequest
path:/get_weblogo/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'csrfmiddlewaretoken': [u'1JeWV17L2Zu550bhL8Q6XVBcvufmRlUX'], u'sites': [u'GGGTGTCGGTCTGACCACTTGAC,CGCCGGTGGTCTGACCACCTGAC,GCTAACTGGTCAGACCACTTGAC,AACCACTGGTAAGACCACTTGAC,GCACACTGGTCTGACCACTTGAC,CACGATTGGTCTTACCACTTGAC,GCTAACTGGTCAGACCACTTGAC']}>,

```

**Comment by ivanerill** [comment]
When does this pop up? Large motifs?

**Comment by sefakilic** [comment]
Closing for now. Will reopen if the problem persists after the new server OS.
