### ISSUE TITLE
[Django] ERROR (EXTERNAL IP): Internal Server Error: /browse/view_reports/species/77/tf/66/all/-1/0

### ISSUE THREAD

**Issue by sefakilic** [ErillLab/collectf#18]
```
Traceback (most recent call last):

  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/local/collecTF/browse/view_reports.py", line 59, in view_reports
    ensemble_report.generate_view_reports_dict(),

AttributeError: 'NoneType' object has no attribute 'generate_view_reports_dict'
```

**Comment by sefakilic** [comment]
Fixed in django-1.9 branch,
