### ISSUE TITLE
[Django] ERROR (EXTERNAL IP): Internal Server Error: /curate/curation/

### ISSUE THREAD

**Issue by sefakilic** [ErillLab/collectf#19]
```
Traceback (most recent call last):

  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)

  File "/local/collecTF/curate/add_curation.py", line 152, in curation
    return view(request)

  File "/usr/lib/python2.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)

  File "/usr/lib/python2.6/site-packages/django/contrib/formtools/wizard/views.py", line 236, in dispatch
    response = super(WizardView, self).dispatch(request, *args, **kwargs)

  File "/usr/lib/python2.6/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)

  File "/usr/lib/python2.6/site-packages/django/contrib/formtools/wizard/views.py", line 289, in post
    if form.is_valid():

  File "/usr/lib/python2.6/site-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)

  File "/usr/lib/python2.6/site-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()

  File "/usr/lib/python2.6/site-packages/django/forms/forms.py", line 273, in full_clean
    self._clean_fields()

  File "/usr/lib/python2.6/site-packages/django/forms/forms.py", line 291, in _clean_fields
    value = getattr(self, 'clean_%s' % name)()

  File "/local/collecTF/curate/forms/add_curation_form.py", line 159, in clean_genome_accession
    return self.clean_genome_accession_helper(genome_accession)

  File "/local/collecTF/curate/forms/add_curation_form.py", line 145, in clean_genome_accession_helper
    if not create_object.make_genome(genome_record, strain_tax):

  File "/local/collecTF/curate/create_object.py", line 86, in make_genome
    genes = bioutils.get_genes(genome_record)

  File "/local/collecTF/base/bioutils.py", line 99, in get_genes
    gids = [get_gene_id(f) for f in gene_features]

  File "/local/collecTF/base/bioutils.py", line 56, in get_gene_id
    while not feature.qualifiers['db_xref'][i].startswith('GeneID:'):

KeyError: 'db_xref'
```

**Comment by sefakilic** [comment]
Resolved in Django 1.9 version of CollecTF
