### ISSUE TITLE
[Django] ERROR (EXTERNAL IP): Internal Server Error: /curate/add_pubmed/

### ISSUE THREAD

**Issue by sefakilic** [ErillLab/collectf#31]
```
Traceback (most recent call last):

  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)

  File "/local/collecTF/curate/add_publication.py", line 72, in pubmed_submission
    return view(request)

  File "/usr/lib/python2.6/site-packages/django/contrib/formtools/preview.py", line 30, in __call__
    return method(request)

  File "/usr/lib/python2.6/site-packages/django/contrib/formtools/preview.py", line 59, in preview_post
    if f.is_valid():

  File "/usr/lib/python2.6/site-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)

  File "/usr/lib/python2.6/site-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()

  File "/usr/lib/python2.6/site-packages/django/forms/forms.py", line 273, in full_clean
    self._clean_fields()

  File "/usr/lib/python2.6/site-packages/django/forms/forms.py", line 291, in _clean_fields
    value = getattr(self, 'clean_%s' % name)()

  File "/local/collecTF/curate/forms/add_publication_form.py", line 37, in clean_pmid
    if not bioutils.get_pubmed(cp):

  File "/local/collecTF/base/bioutils.py", line 25, in get_pubmed
    record = Entrez.read(handle)

  File "/usr/lib64/python2.6/site-packages/Bio/Entrez/__init__.py", line 374, in read
    from .Parser import DataHandler

  File "/usr/lib64/python2.6/site-packages/Bio/Entrez/Parser.py", line 154, in <module>
    class DataHandler(object):

  File "/usr/lib64/python2.6/site-packages/Bio/Entrez/Parser.py", line 173, in DataHandler
    raise exception

OSError: [Errno 13] Permission denied: '/root/.config'


```

**Comment by sefakilic** [comment]
Resolved in Django 1.9 version of CollecTF.
