### ISSUE TITLE
Internal Server Error: /browse/motif_similarity_measure/

### ISSUE THREAD

**Issue by sefakilic** [ErillLab/collectf#32]
```
Traceback (most recent call last):

  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/local/collecTF/browse/compare.py", line 133, in motif_sim_measure
    boxplot, hist = levenshtein_measure(sites_a, sites_b)

  File "/local/collecTF/browse/compare.py", line 180, in levenshtein_measure
    label=[r'$M_a$ vs $M_a$', r'$M_a$ vs $M_b$', r'$M_b$ vs $M_b$'],

  File "/usr/lib64/python2.6/site-packages/matplotlib/pyplot.py", line 2008, in hist
    ret = ax.hist(x, bins, range, normed, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, **kwargs)

  File "/usr/lib64/python2.6/site-packages/matplotlib/axes.py", line 7116, in hist
    m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)

  File "/usr/lib64/python2.6/site-packages/numpy/lib/function_base.py", line 176, in histogram
    mn, mx = [mi+0.0 for mi in range]

TypeError: can only concatenate list (not "float") to list

```

**Comment by sefakilic** [comment]
Fixed in django-1.9 branch.
